### ISSUE TITLE
Handcrafting an Isomorphic Redux Application

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-react#4]
Milo wrote this *excellent* tutorial:
https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4

**Comment by iancrowther** [comment]
what do you need help with?

**Comment by nelsonic** [comment]
Good point @iancrowther I applied the `help wanted` because I need help deciding if *this* ("Redux") is the future or fad. I still find JSX "*hacky*" at best. And for a complete beginner there is so much *syntax* and vocabulary that it feels like "*emperor's new clothes*" ... what are your thoughts?

**Comment by nelsonic** [comment]
It's worth reading all of @gaearon's posts on the subject: https://medium.com/@dan_abramov

**Comment by gaearon** [comment]
Redux is not related to JSX in any way so your comment confused me a little.
Anyway, [here's a good article on JSX](https://medium.com/@housecor/react-s-jsx-the-other-side-of-the-coin-2ace7ab62b98). As for Redux, it's neither “future” nor “fad”—just one possible way of organizing state mutations. It's also nothing new: see [Elm Architecture](https://github.com/evancz/elm-architecture-tutorial/) which matches Redux in some ways.

**Comment by nelsonic** [comment]
@gaearon thanks for the insight. :+1:

**Comment by gaearon** [comment]
One more thing about Redux: if you remove sanity checks and comments, it's [99 lines](https://gist.github.com/gaearon/ffd88b0e4f00b22c3159).
Can't be that much to learn ;-)

**Comment by iancrowther** [comment]
good shares @gaearon 

I don't really have an educated opinion on the matter as Ive not spent any time tinkering.  does that mean I consider it a fad? possibly, but I think it's more like I have not found a "need" for it as traditional patterns have been sufficient.

i need a "html ain't broke" bumper sticker!

**Comment by nelsonic** [comment]
Moved to: https://github.com/nelsonic/learn-redux/issues/13
