### ISSUE TITLE
Full-Stack Redux Tutorial

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-react#5]
Test-First Development with Redux, React, and Immutable by @teropa
http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html

**Comment by sofer** [comment]
@nelsonic I also like the [Getting Started with Redux](https://egghead.io/series/getting-started-with-redux) tutorial by Dan Abramov, which starts off with unit tests (although conveniently forgets about them after the first few sections).

**Comment by nelsonic** [comment]
@sofer `() => ` https://github.com/nelsonic/learn-redux/blob/master/egghead.io_video_tutorial_notes.md :wink:

**Comment by sofer** [comment]
:+1:

**Comment by nelsonic** [comment]
See: https://github.com/dwyl/learn-redux
