### ISSUE TITLE
React Secret DOM - Do Not Use

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-react#7]
![react js__secret_dom_do_not_use_or_you_will_be_fired](https://cloud.githubusercontent.com/assets/194400/12078469/ad95d04c-b20b-11e5-8ddf-a33d90549549.png)
see: https://cdnjs.cloudflare.com/ajax/libs/react/0.14.5/react-dom.min.js

> Do we need to explain this to beginners?

**Comment by NataliaLKB** [comment]
What a find! :mag:

**Comment by Joshuagollaher** [comment]
i found that a few weeks ago!

**Comment by StarBlizard** [comment]
Im too! Jajajaja

**Comment by nelsonic** [comment]
Anyway ... 
not an "_issue_" with `this` repo. 
so closing.
