### ISSUE TITLE
Hello World in React

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-react#8]
http://www.uxnjs.com/hello-world-with-react/
Need to add tests tho...

**Comment by nelsonic** [comment]
@perborgen wrote a good post on Medium: https://medium.com/learning-new-stuff/building-your-first-react-js-app-d53b0c98dc

**Comment by curioustushar** [comment]
Made react sample projects repo with 17 projects which will good for anyone starting with react.js, will be adding more projects as my learning progress.

https://github.com/curioustushar/react-sample-projects

**Comment by nelsonic** [comment]
@curioustushar please consider watching "Rethinking Reactivity": https://youtu.be/AdNJ3fydeao
